workflows:
  android-release:
    name: Build Android Release
    max_build_duration: 60

    environment:
      flutter: false
      node: 18
      java: 17
      groups:
        - keystore_credentials
      vars:
        MYAPP_UPLOAD_STORE_FILE: keystore.jks
        MYAPP_UPLOAD_KEY_ALIAS: upload

    scripts:
      - name: Hard Clean Environment
        script: |
          echo "🧹 Limpando caches e daemons..."
          rm -rf ~/.gradle/caches
          rm -rf ~/.gradle/daemon
          rm -rf ~/.gradle/native
          rm -rf ~/.gradle/wrapper
          rm -rf android/.gradle
          rm -rf android/app/build
          rm -rf node_modules

          echo "Reinstalando dependências..."
          npm install --legacy-peer-deps

      - name: Install Android dependencies
        script: |
          echo "Instalando dependências Android..."
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "build-tools;34.0.0" "platforms;android-34"

      - name: Build Android Release
        script: |
          echo "Iniciando build Android..."
          cd android
          ./gradlew clean
          ./gradlew assembleRelease -x lint -Pandroid.injected.testOnly=false

    artifacts:
      - android/app/build/outputs/**/*.apk
      - android/app/build/outputs/**/*.aab
