workflows:
  android-release:
    name: Build Android Release
    max_build_duration: 60

    environment:
      node: "18"
      java: "17"
      groups:
        - keystore_credentials
      vars:
        MYAPP_UPLOAD_STORE_FILE: keystore.jks
        MYAPP_UPLOAD_KEY_ALIAS: upload

    cache:
      cache_paths:
        - ~/.gradle
        - ~/.cache
        - node_modules

    scripts:
      - name: Install Node dependencies
        script: |
          echo "Instalando dependências NPM..."
          npm install --legacy-peer-deps

      - name: Install Android dependencies
        script: |
          echo "Instalando dependências Android..."
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "build-tools;34.0.0" "platforms;android-34"

      - name: Build Android Release
        script: |
          echo "Iniciando build Android..."
          cd android
          ./gradlew clean
          ./gradlew assembleRelease -x lint -Pandroid.injected.testOnly=false

    artifacts:
      - android/app/build/outputs/**/*.apk
      - android/app/build/outputs/**/*.aab
