workflows:
  android-release:
    name: Android Release Build
    max_build_duration: 60
    environment:
      vars:
        PACKAGE_NAME: "com.meuappcontrole"
      java: 17
      node: 18
      yarn: true
    scripts:
      - name: Install dependencies
        script: |
          yarn install --frozen-lockfile

      - name: Install Android dependencies
        script: |
          sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      - name: Build Android release
        script: |
          cd android
          ./gradlew assembleRelease

    artifacts:
      - android/app/build/outputs/**/*.apk
      - android/app/build/outputs/**/*.aab

    publishing:
      email:
        recipients:
          - "seu-email@example.com"
