workflows:
  android-release:
    name: Build Android Release
    max_build_duration: 60

    environment:
      node: 18
      java: 17
      groups:
        - keystore_credentials
      vars:
        MYAPP_UPLOAD_STORE_FILE: keystore.jks
        MYAPP_UPLOAD_KEY_ALIAS: upload

    scripts:

      - name: Clean environment
        script: |
          echo "🧹 Limpando caches..."
          rm -rf ~/.gradle/caches
          rm -rf ~/.gradle/daemon
          rm -rf android/.gradle
          rm -rf android/app/build
          rm -rf node_modules

          echo "📦 Instalando dependências..."
          npm install --legacy-peer-deps

      - name: Install Android SDK
        script: |
          echo "📱 Instalando Android SDK..."
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "build-tools;34.0.0" "platforms;android-34"

      - name: Build Release
        script: |
          echo "🚀 Buildando APK..."
          cd android
          ./gradlew clean
          ./gradlew assembleRelease -x lint -Pandroid.injected.testOnly=false

    artifacts:
      - android/app/build/outputs/**/*.apk
      - android/app/build/outputs/**/*.aab
