workflows:
  android-release:
    name: Build Android Release
    max_build_duration: 60
    environment:
      vars:
        MYAPP_UPLOAD_STORE_FILE: $MYAPP_UPLOAD_STORE_FILE
        MYAPP_UPLOAD_STORE_PASSWORD: $MYAPP_UPLOAD_STORE_PASSWORD
        MYAPP_UPLOAD_KEY_ALIAS: $MYAPP_UPLOAD_KEY_ALIAS
        MYAPP_UPLOAD_KEY_PASSWORD: $MYAPP_UPLOAD_KEY_PASSWORD
      node: "lts/*"
      java: "17"
    scripts:
      - name: Install system deps
        script: |
          echo "Instalando dependências do projeto..."
          npm ci
      - name: Prepare Android SDK
        script: |
          echo "Android SDK presumido presente no runner Codemagic"
      - name: Run Android release build
        script: |
          set -e
          cd android
          ./gradlew assembleRelease -Pandroid.injected.testOnly=false
    artifacts:
      - android/app/build/outputs/**/*.apk
      - android/app/build/outputs/**/*.aab
