workflows:
  android-release:
    name: Android Release Build
    max_build_duration: 60

    environment:
      java: 17
      node: 18
      vars:
        PACKAGE_NAME: "com.meuappcontrole"

    scripts:
      - name: Instalar dependências
        script: |
          npm install --legacy-peer-deps

      - name: Build Android Release
        script: |
          cd android
          ./gradlew clean
          ./gradlew assembleRelease

    artifacts:
      - android/app/build/outputs/**/*.apk
      - android/app/build/outputs/**/*.aab

    publishing:
      email:
        recipients:
          - "seu-email@example.com"
